// This is a generated file, do not edit!
// Generated by R.swift, see https://github.com/mac-cain13/R.swift

import Foundation
import Rswift
import UIKit

/// This `R` struct is code generateted, and contains references to static resources.
struct R: Rswift.Validatable {
  static func validate() throws {
    try intern.validate()
  }
  
  /// This `R.color` struct is generated, and contains static references to 0 color palettes.
  struct color {
    private init() {}
  }
  
  /// This `R.file` struct is generated, and contains static references to 5 files.
  struct file {
    /// Resource file `app_font.ttc`.
    static let app_fontTtc = FileResource(bundle: _R.hostingBundle, name: "app_font", pathExtension: "ttc")
    /// Resource file `DefaultPlayerData.json`.
    static let defaultPlayerDataJson = FileResource(bundle: _R.hostingBundle, name: "DefaultPlayerData", pathExtension: "json")
    /// Resource file `GameDataQA1.json`.
    static let gameDataQA1Json = FileResource(bundle: _R.hostingBundle, name: "GameDataQA1", pathExtension: "json")
    /// Resource file `GameDataQA2.json`.
    static let gameDataQA2Json = FileResource(bundle: _R.hostingBundle, name: "GameDataQA2", pathExtension: "json")
    /// Resource file `iTunesArtwork@2x.png`.
    static let iTunesArtwork2xPng = FileResource(bundle: _R.hostingBundle, name: "iTunesArtwork@2x", pathExtension: "png")
    
    /// `bundle.URLForResource("app_font", withExtension: "ttc")`
    static func app_fontTtc(_: Void) -> NSURL? {
      let fileResource = R.file.app_fontTtc
      return fileResource.bundle.URLForResource(fileResource)
    }
    
    /// `bundle.URLForResource("DefaultPlayerData", withExtension: "json")`
    static func defaultPlayerDataJson(_: Void) -> NSURL? {
      let fileResource = R.file.defaultPlayerDataJson
      return fileResource.bundle.URLForResource(fileResource)
    }
    
    /// `bundle.URLForResource("GameDataQA1", withExtension: "json")`
    static func gameDataQA1Json(_: Void) -> NSURL? {
      let fileResource = R.file.gameDataQA1Json
      return fileResource.bundle.URLForResource(fileResource)
    }
    
    /// `bundle.URLForResource("GameDataQA2", withExtension: "json")`
    static func gameDataQA2Json(_: Void) -> NSURL? {
      let fileResource = R.file.gameDataQA2Json
      return fileResource.bundle.URLForResource(fileResource)
    }
    
    /// `bundle.URLForResource("iTunesArtwork@2x", withExtension: "png")`
    static func iTunesArtwork2xPng(_: Void) -> NSURL? {
      let fileResource = R.file.iTunesArtwork2xPng
      return fileResource.bundle.URLForResource(fileResource)
    }
    
    private init() {}
  }
  
  /// This `R.font` struct is generated, and contains static references to 0 fonts.
  struct font {
    private init() {}
  }
  
  /// This `R.image` struct is generated, and contains static references to 125 images.
  struct image {
    /// Image `background_blue`.
    static let background_blue = ImageResource(bundle: _R.hostingBundle, name: "background_blue")
    /// Image `background_green`.
    static let background_green = ImageResource(bundle: _R.hostingBundle, name: "background_green")
    /// Image `background_hand_odds_green`.
    static let background_hand_odds_green = ImageResource(bundle: _R.hostingBundle, name: "background_hand_odds_green")
    /// Image `background_hand_odds_grey`.
    static let background_hand_odds_grey = ImageResource(bundle: _R.hostingBundle, name: "background_hand_odds_grey")
    /// Image `background_table_level_1`.
    static let background_table_level_1 = ImageResource(bundle: _R.hostingBundle, name: "background_table_level_1")
    /// Image `background_table_level_2`.
    static let background_table_level_2 = ImageResource(bundle: _R.hostingBundle, name: "background_table_level_2")
    /// Image `background_table_level_3`.
    static let background_table_level_3 = ImageResource(bundle: _R.hostingBundle, name: "background_table_level_3")
    /// Image `background_table_level_4`.
    static let background_table_level_4 = ImageResource(bundle: _R.hostingBundle, name: "background_table_level_4")
    /// Image `background_table_level_5`.
    static let background_table_level_5 = ImageResource(bundle: _R.hostingBundle, name: "background_table_level_5")
    /// Image `background_table_level_6`.
    static let background_table_level_6 = ImageResource(bundle: _R.hostingBundle, name: "background_table_level_6")
    /// Image `background_table_level_7`.
    static let background_table_level_7 = ImageResource(bundle: _R.hostingBundle, name: "background_table_level_7")
    /// Image `background_table_locked`.
    static let background_table_locked = ImageResource(bundle: _R.hostingBundle, name: "background_table_locked")
    /// Image `banner_standard`.
    static let banner_standard = ImageResource(bundle: _R.hostingBundle, name: "banner_standard")
    /// Image `banner_unlock_level_2`.
    static let banner_unlock_level_2 = ImageResource(bundle: _R.hostingBundle, name: "banner_unlock_level_2")
    /// Image `banner_unlock_level_3`.
    static let banner_unlock_level_3 = ImageResource(bundle: _R.hostingBundle, name: "banner_unlock_level_3")
    /// Image `banner_unlock_level_4`.
    static let banner_unlock_level_4 = ImageResource(bundle: _R.hostingBundle, name: "banner_unlock_level_4")
    /// Image `banner_unlock_level_5`.
    static let banner_unlock_level_5 = ImageResource(bundle: _R.hostingBundle, name: "banner_unlock_level_5")
    /// Image `banner_unlock_level_6`.
    static let banner_unlock_level_6 = ImageResource(bundle: _R.hostingBundle, name: "banner_unlock_level_6")
    /// Image `banner_unlock_level_7`.
    static let banner_unlock_level_7 = ImageResource(bundle: _R.hostingBundle, name: "banner_unlock_level_7")
    /// Image `button_menu_play_normal`.
    static let button_menu_play_normal = ImageResource(bundle: _R.hostingBundle, name: "button_menu_play_normal")
    /// Image `button_menu_play_selected`.
    static let button_menu_play_selected = ImageResource(bundle: _R.hostingBundle, name: "button_menu_play_selected")
    /// Image `button_menu_share_normal`.
    static let button_menu_share_normal = ImageResource(bundle: _R.hostingBundle, name: "button_menu_share_normal")
    /// Image `button_menu_share_selected`.
    static let button_menu_share_selected = ImageResource(bundle: _R.hostingBundle, name: "button_menu_share_selected")
    /// Image `button_menu_stats_normal`.
    static let button_menu_stats_normal = ImageResource(bundle: _R.hostingBundle, name: "button_menu_stats_normal")
    /// Image `button_menu_stats_selected`.
    static let button_menu_stats_selected = ImageResource(bundle: _R.hostingBundle, name: "button_menu_stats_selected")
    /// Image `card_back`.
    static let card_back = ImageResource(bundle: _R.hostingBundle, name: "card_back")
    /// Image `card_suit0_rank0`.
    static let card_suit0_rank0 = ImageResource(bundle: _R.hostingBundle, name: "card_suit0_rank0")
    /// Image `card_suit0_rank1`.
    static let card_suit0_rank1 = ImageResource(bundle: _R.hostingBundle, name: "card_suit0_rank1")
    /// Image `card_suit0_rank10`.
    static let card_suit0_rank10 = ImageResource(bundle: _R.hostingBundle, name: "card_suit0_rank10")
    /// Image `card_suit0_rank11`.
    static let card_suit0_rank11 = ImageResource(bundle: _R.hostingBundle, name: "card_suit0_rank11")
    /// Image `card_suit0_rank12`.
    static let card_suit0_rank12 = ImageResource(bundle: _R.hostingBundle, name: "card_suit0_rank12")
    /// Image `card_suit0_rank2`.
    static let card_suit0_rank2 = ImageResource(bundle: _R.hostingBundle, name: "card_suit0_rank2")
    /// Image `card_suit0_rank3`.
    static let card_suit0_rank3 = ImageResource(bundle: _R.hostingBundle, name: "card_suit0_rank3")
    /// Image `card_suit0_rank4`.
    static let card_suit0_rank4 = ImageResource(bundle: _R.hostingBundle, name: "card_suit0_rank4")
    /// Image `card_suit0_rank5`.
    static let card_suit0_rank5 = ImageResource(bundle: _R.hostingBundle, name: "card_suit0_rank5")
    /// Image `card_suit0_rank6`.
    static let card_suit0_rank6 = ImageResource(bundle: _R.hostingBundle, name: "card_suit0_rank6")
    /// Image `card_suit0_rank7`.
    static let card_suit0_rank7 = ImageResource(bundle: _R.hostingBundle, name: "card_suit0_rank7")
    /// Image `card_suit0_rank8`.
    static let card_suit0_rank8 = ImageResource(bundle: _R.hostingBundle, name: "card_suit0_rank8")
    /// Image `card_suit0_rank9`.
    static let card_suit0_rank9 = ImageResource(bundle: _R.hostingBundle, name: "card_suit0_rank9")
    /// Image `card_suit1_rank0`.
    static let card_suit1_rank0 = ImageResource(bundle: _R.hostingBundle, name: "card_suit1_rank0")
    /// Image `card_suit1_rank1`.
    static let card_suit1_rank1 = ImageResource(bundle: _R.hostingBundle, name: "card_suit1_rank1")
    /// Image `card_suit1_rank10`.
    static let card_suit1_rank10 = ImageResource(bundle: _R.hostingBundle, name: "card_suit1_rank10")
    /// Image `card_suit1_rank11`.
    static let card_suit1_rank11 = ImageResource(bundle: _R.hostingBundle, name: "card_suit1_rank11")
    /// Image `card_suit1_rank12`.
    static let card_suit1_rank12 = ImageResource(bundle: _R.hostingBundle, name: "card_suit1_rank12")
    /// Image `card_suit1_rank2`.
    static let card_suit1_rank2 = ImageResource(bundle: _R.hostingBundle, name: "card_suit1_rank2")
    /// Image `card_suit1_rank3`.
    static let card_suit1_rank3 = ImageResource(bundle: _R.hostingBundle, name: "card_suit1_rank3")
    /// Image `card_suit1_rank4`.
    static let card_suit1_rank4 = ImageResource(bundle: _R.hostingBundle, name: "card_suit1_rank4")
    /// Image `card_suit1_rank5`.
    static let card_suit1_rank5 = ImageResource(bundle: _R.hostingBundle, name: "card_suit1_rank5")
    /// Image `card_suit1_rank6`.
    static let card_suit1_rank6 = ImageResource(bundle: _R.hostingBundle, name: "card_suit1_rank6")
    /// Image `card_suit1_rank7`.
    static let card_suit1_rank7 = ImageResource(bundle: _R.hostingBundle, name: "card_suit1_rank7")
    /// Image `card_suit1_rank8`.
    static let card_suit1_rank8 = ImageResource(bundle: _R.hostingBundle, name: "card_suit1_rank8")
    /// Image `card_suit1_rank9`.
    static let card_suit1_rank9 = ImageResource(bundle: _R.hostingBundle, name: "card_suit1_rank9")
    /// Image `card_suit2_rank0`.
    static let card_suit2_rank0 = ImageResource(bundle: _R.hostingBundle, name: "card_suit2_rank0")
    /// Image `card_suit2_rank1`.
    static let card_suit2_rank1 = ImageResource(bundle: _R.hostingBundle, name: "card_suit2_rank1")
    /// Image `card_suit2_rank10`.
    static let card_suit2_rank10 = ImageResource(bundle: _R.hostingBundle, name: "card_suit2_rank10")
    /// Image `card_suit2_rank11`.
    static let card_suit2_rank11 = ImageResource(bundle: _R.hostingBundle, name: "card_suit2_rank11")
    /// Image `card_suit2_rank12`.
    static let card_suit2_rank12 = ImageResource(bundle: _R.hostingBundle, name: "card_suit2_rank12")
    /// Image `card_suit2_rank2`.
    static let card_suit2_rank2 = ImageResource(bundle: _R.hostingBundle, name: "card_suit2_rank2")
    /// Image `card_suit2_rank3`.
    static let card_suit2_rank3 = ImageResource(bundle: _R.hostingBundle, name: "card_suit2_rank3")
    /// Image `card_suit2_rank4`.
    static let card_suit2_rank4 = ImageResource(bundle: _R.hostingBundle, name: "card_suit2_rank4")
    /// Image `card_suit2_rank5`.
    static let card_suit2_rank5 = ImageResource(bundle: _R.hostingBundle, name: "card_suit2_rank5")
    /// Image `card_suit2_rank6`.
    static let card_suit2_rank6 = ImageResource(bundle: _R.hostingBundle, name: "card_suit2_rank6")
    /// Image `card_suit2_rank7`.
    static let card_suit2_rank7 = ImageResource(bundle: _R.hostingBundle, name: "card_suit2_rank7")
    /// Image `card_suit2_rank8`.
    static let card_suit2_rank8 = ImageResource(bundle: _R.hostingBundle, name: "card_suit2_rank8")
    /// Image `card_suit2_rank9`.
    static let card_suit2_rank9 = ImageResource(bundle: _R.hostingBundle, name: "card_suit2_rank9")
    /// Image `card_suit3_rank0`.
    static let card_suit3_rank0 = ImageResource(bundle: _R.hostingBundle, name: "card_suit3_rank0")
    /// Image `card_suit3_rank1`.
    static let card_suit3_rank1 = ImageResource(bundle: _R.hostingBundle, name: "card_suit3_rank1")
    /// Image `card_suit3_rank10`.
    static let card_suit3_rank10 = ImageResource(bundle: _R.hostingBundle, name: "card_suit3_rank10")
    /// Image `card_suit3_rank11`.
    static let card_suit3_rank11 = ImageResource(bundle: _R.hostingBundle, name: "card_suit3_rank11")
    /// Image `card_suit3_rank12`.
    static let card_suit3_rank12 = ImageResource(bundle: _R.hostingBundle, name: "card_suit3_rank12")
    /// Image `card_suit3_rank2`.
    static let card_suit3_rank2 = ImageResource(bundle: _R.hostingBundle, name: "card_suit3_rank2")
    /// Image `card_suit3_rank3`.
    static let card_suit3_rank3 = ImageResource(bundle: _R.hostingBundle, name: "card_suit3_rank3")
    /// Image `card_suit3_rank4`.
    static let card_suit3_rank4 = ImageResource(bundle: _R.hostingBundle, name: "card_suit3_rank4")
    /// Image `card_suit3_rank5`.
    static let card_suit3_rank5 = ImageResource(bundle: _R.hostingBundle, name: "card_suit3_rank5")
    /// Image `card_suit3_rank6`.
    static let card_suit3_rank6 = ImageResource(bundle: _R.hostingBundle, name: "card_suit3_rank6")
    /// Image `card_suit3_rank7`.
    static let card_suit3_rank7 = ImageResource(bundle: _R.hostingBundle, name: "card_suit3_rank7")
    /// Image `card_suit3_rank8`.
    static let card_suit3_rank8 = ImageResource(bundle: _R.hostingBundle, name: "card_suit3_rank8")
    /// Image `card_suit3_rank9`.
    static let card_suit3_rank9 = ImageResource(bundle: _R.hostingBundle, name: "card_suit3_rank9")
    /// Image `iTunesArtwork`.
    static let iTunesArtwork = ImageResource(bundle: _R.hostingBundle, name: "iTunesArtwork")
    /// Image `icon_chip_blue`.
    static let icon_chip_blue = ImageResource(bundle: _R.hostingBundle, name: "icon_chip_blue")
    /// Image `icon_done_blue`.
    static let icon_done_blue = ImageResource(bundle: _R.hostingBundle, name: "icon_done_blue")
    /// Image `icon_done_green`.
    static let icon_done_green = ImageResource(bundle: _R.hostingBundle, name: "icon_done_green")
    /// Image `icon_leaderboards_blue`.
    static let icon_leaderboards_blue = ImageResource(bundle: _R.hostingBundle, name: "icon_leaderboards_blue")
    /// Image `icon_play`.
    static let icon_play = ImageResource(bundle: _R.hostingBundle, name: "icon_play")
    /// Image `icon_share_facebook_large`.
    static let icon_share_facebook_large = ImageResource(bundle: _R.hostingBundle, name: "icon_share_facebook_large")
    /// Image `icon_share_facebook_small`.
    static let icon_share_facebook_small = ImageResource(bundle: _R.hostingBundle, name: "icon_share_facebook_small")
    /// Image `icon_share_instagram_large`.
    static let icon_share_instagram_large = ImageResource(bundle: _R.hostingBundle, name: "icon_share_instagram_large")
    /// Image `icon_share_instagram_small`.
    static let icon_share_instagram_small = ImageResource(bundle: _R.hostingBundle, name: "icon_share_instagram_small")
    /// Image `icon_share_twitter_large`.
    static let icon_share_twitter_large = ImageResource(bundle: _R.hostingBundle, name: "icon_share_twitter_large")
    /// Image `icon_share_twitter_small`.
    static let icon_share_twitter_small = ImageResource(bundle: _R.hostingBundle, name: "icon_share_twitter_small")
    /// Image `icon_stats`.
    static let icon_stats = ImageResource(bundle: _R.hostingBundle, name: "icon_stats")
    /// Image `icon_stats_blue`.
    static let icon_stats_blue = ImageResource(bundle: _R.hostingBundle, name: "icon_stats_blue")
    /// Image `icon_stats_green`.
    static let icon_stats_green = ImageResource(bundle: _R.hostingBundle, name: "icon_stats_green")
    /// Image `launch_screen`.
    static let launch_screen = ImageResource(bundle: _R.hostingBundle, name: "launch_screen")
    /// Image `overlay_letters_blue`.
    static let overlay_letters_blue = ImageResource(bundle: _R.hostingBundle, name: "overlay_letters_blue")
    /// Image `overlay_stats_level_1`.
    static let overlay_stats_level_1 = ImageResource(bundle: _R.hostingBundle, name: "overlay_stats_level_1")
    /// Image `overlay_stats_level_2`.
    static let overlay_stats_level_2 = ImageResource(bundle: _R.hostingBundle, name: "overlay_stats_level_2")
    /// Image `overlay_stats_level_3`.
    static let overlay_stats_level_3 = ImageResource(bundle: _R.hostingBundle, name: "overlay_stats_level_3")
    /// Image `overlay_stats_level_4`.
    static let overlay_stats_level_4 = ImageResource(bundle: _R.hostingBundle, name: "overlay_stats_level_4")
    /// Image `overlay_stats_level_5`.
    static let overlay_stats_level_5 = ImageResource(bundle: _R.hostingBundle, name: "overlay_stats_level_5")
    /// Image `overlay_stats_level_6`.
    static let overlay_stats_level_6 = ImageResource(bundle: _R.hostingBundle, name: "overlay_stats_level_6")
    /// Image `overlay_stats_level_7`.
    static let overlay_stats_level_7 = ImageResource(bundle: _R.hostingBundle, name: "overlay_stats_level_7")
    /// Image `overlay_stats_level_overall`.
    static let overlay_stats_level_overall = ImageResource(bundle: _R.hostingBundle, name: "overlay_stats_level_overall")
    /// Image `overlay_stats_locked_level_2`.
    static let overlay_stats_locked_level_2 = ImageResource(bundle: _R.hostingBundle, name: "overlay_stats_locked_level_2")
    /// Image `overlay_stats_locked_level_3`.
    static let overlay_stats_locked_level_3 = ImageResource(bundle: _R.hostingBundle, name: "overlay_stats_locked_level_3")
    /// Image `overlay_stats_locked_level_4`.
    static let overlay_stats_locked_level_4 = ImageResource(bundle: _R.hostingBundle, name: "overlay_stats_locked_level_4")
    /// Image `overlay_stats_locked_level_5`.
    static let overlay_stats_locked_level_5 = ImageResource(bundle: _R.hostingBundle, name: "overlay_stats_locked_level_5")
    /// Image `overlay_stats_locked_level_6`.
    static let overlay_stats_locked_level_6 = ImageResource(bundle: _R.hostingBundle, name: "overlay_stats_locked_level_6")
    /// Image `overlay_stats_locked_level_7`.
    static let overlay_stats_locked_level_7 = ImageResource(bundle: _R.hostingBundle, name: "overlay_stats_locked_level_7")
    /// Image `overlay_table_level_1`.
    static let overlay_table_level_1 = ImageResource(bundle: _R.hostingBundle, name: "overlay_table_level_1")
    /// Image `overlay_table_level_2`.
    static let overlay_table_level_2 = ImageResource(bundle: _R.hostingBundle, name: "overlay_table_level_2")
    /// Image `overlay_table_level_3`.
    static let overlay_table_level_3 = ImageResource(bundle: _R.hostingBundle, name: "overlay_table_level_3")
    /// Image `overlay_table_level_4`.
    static let overlay_table_level_4 = ImageResource(bundle: _R.hostingBundle, name: "overlay_table_level_4")
    /// Image `overlay_table_level_5`.
    static let overlay_table_level_5 = ImageResource(bundle: _R.hostingBundle, name: "overlay_table_level_5")
    /// Image `overlay_table_level_6`.
    static let overlay_table_level_6 = ImageResource(bundle: _R.hostingBundle, name: "overlay_table_level_6")
    /// Image `overlay_table_level_7`.
    static let overlay_table_level_7 = ImageResource(bundle: _R.hostingBundle, name: "overlay_table_level_7")
    /// Image `overlay_table_locked_level_2`.
    static let overlay_table_locked_level_2 = ImageResource(bundle: _R.hostingBundle, name: "overlay_table_locked_level_2")
    /// Image `overlay_table_locked_level_3`.
    static let overlay_table_locked_level_3 = ImageResource(bundle: _R.hostingBundle, name: "overlay_table_locked_level_3")
    /// Image `overlay_table_locked_level_4`.
    static let overlay_table_locked_level_4 = ImageResource(bundle: _R.hostingBundle, name: "overlay_table_locked_level_4")
    /// Image `overlay_table_locked_level_5`.
    static let overlay_table_locked_level_5 = ImageResource(bundle: _R.hostingBundle, name: "overlay_table_locked_level_5")
    /// Image `overlay_table_locked_level_6`.
    static let overlay_table_locked_level_6 = ImageResource(bundle: _R.hostingBundle, name: "overlay_table_locked_level_6")
    /// Image `overlay_table_locked_level_7`.
    static let overlay_table_locked_level_7 = ImageResource(bundle: _R.hostingBundle, name: "overlay_table_locked_level_7")
    /// Image `shadow_blue`.
    static let shadow_blue = ImageResource(bundle: _R.hostingBundle, name: "shadow_blue")
    /// Image `share_screen_instagram`.
    static let share_screen_instagram = ImageResource(bundle: _R.hostingBundle, name: "share_screen_instagram")
    /// Image `share_screen_twitter`.
    static let share_screen_twitter = ImageResource(bundle: _R.hostingBundle, name: "share_screen_twitter")
    
    /// `UIImage(named: "background_blue", bundle: ..., traitCollection: ...)`
    static func background_blue(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.background_blue, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "background_green", bundle: ..., traitCollection: ...)`
    static func background_green(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.background_green, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "background_hand_odds_green", bundle: ..., traitCollection: ...)`
    static func background_hand_odds_green(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.background_hand_odds_green, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "background_hand_odds_grey", bundle: ..., traitCollection: ...)`
    static func background_hand_odds_grey(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.background_hand_odds_grey, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "background_table_level_1", bundle: ..., traitCollection: ...)`
    static func background_table_level_1(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.background_table_level_1, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "background_table_level_2", bundle: ..., traitCollection: ...)`
    static func background_table_level_2(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.background_table_level_2, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "background_table_level_3", bundle: ..., traitCollection: ...)`
    static func background_table_level_3(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.background_table_level_3, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "background_table_level_4", bundle: ..., traitCollection: ...)`
    static func background_table_level_4(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.background_table_level_4, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "background_table_level_5", bundle: ..., traitCollection: ...)`
    static func background_table_level_5(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.background_table_level_5, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "background_table_level_6", bundle: ..., traitCollection: ...)`
    static func background_table_level_6(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.background_table_level_6, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "background_table_level_7", bundle: ..., traitCollection: ...)`
    static func background_table_level_7(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.background_table_level_7, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "background_table_locked", bundle: ..., traitCollection: ...)`
    static func background_table_locked(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.background_table_locked, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "banner_standard", bundle: ..., traitCollection: ...)`
    static func banner_standard(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.banner_standard, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "banner_unlock_level_2", bundle: ..., traitCollection: ...)`
    static func banner_unlock_level_2(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.banner_unlock_level_2, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "banner_unlock_level_3", bundle: ..., traitCollection: ...)`
    static func banner_unlock_level_3(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.banner_unlock_level_3, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "banner_unlock_level_4", bundle: ..., traitCollection: ...)`
    static func banner_unlock_level_4(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.banner_unlock_level_4, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "banner_unlock_level_5", bundle: ..., traitCollection: ...)`
    static func banner_unlock_level_5(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.banner_unlock_level_5, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "banner_unlock_level_6", bundle: ..., traitCollection: ...)`
    static func banner_unlock_level_6(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.banner_unlock_level_6, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "banner_unlock_level_7", bundle: ..., traitCollection: ...)`
    static func banner_unlock_level_7(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.banner_unlock_level_7, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "button_menu_play_normal", bundle: ..., traitCollection: ...)`
    static func button_menu_play_normal(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.button_menu_play_normal, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "button_menu_play_selected", bundle: ..., traitCollection: ...)`
    static func button_menu_play_selected(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.button_menu_play_selected, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "button_menu_share_normal", bundle: ..., traitCollection: ...)`
    static func button_menu_share_normal(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.button_menu_share_normal, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "button_menu_share_selected", bundle: ..., traitCollection: ...)`
    static func button_menu_share_selected(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.button_menu_share_selected, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "button_menu_stats_normal", bundle: ..., traitCollection: ...)`
    static func button_menu_stats_normal(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.button_menu_stats_normal, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "button_menu_stats_selected", bundle: ..., traitCollection: ...)`
    static func button_menu_stats_selected(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.button_menu_stats_selected, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "card_back", bundle: ..., traitCollection: ...)`
    static func card_back(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.card_back, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "card_suit0_rank0", bundle: ..., traitCollection: ...)`
    static func card_suit0_rank0(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.card_suit0_rank0, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "card_suit0_rank1", bundle: ..., traitCollection: ...)`
    static func card_suit0_rank1(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.card_suit0_rank1, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "card_suit0_rank10", bundle: ..., traitCollection: ...)`
    static func card_suit0_rank10(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.card_suit0_rank10, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "card_suit0_rank11", bundle: ..., traitCollection: ...)`
    static func card_suit0_rank11(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.card_suit0_rank11, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "card_suit0_rank12", bundle: ..., traitCollection: ...)`
    static func card_suit0_rank12(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.card_suit0_rank12, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "card_suit0_rank2", bundle: ..., traitCollection: ...)`
    static func card_suit0_rank2(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.card_suit0_rank2, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "card_suit0_rank3", bundle: ..., traitCollection: ...)`
    static func card_suit0_rank3(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.card_suit0_rank3, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "card_suit0_rank4", bundle: ..., traitCollection: ...)`
    static func card_suit0_rank4(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.card_suit0_rank4, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "card_suit0_rank5", bundle: ..., traitCollection: ...)`
    static func card_suit0_rank5(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.card_suit0_rank5, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "card_suit0_rank6", bundle: ..., traitCollection: ...)`
    static func card_suit0_rank6(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.card_suit0_rank6, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "card_suit0_rank7", bundle: ..., traitCollection: ...)`
    static func card_suit0_rank7(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.card_suit0_rank7, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "card_suit0_rank8", bundle: ..., traitCollection: ...)`
    static func card_suit0_rank8(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.card_suit0_rank8, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "card_suit0_rank9", bundle: ..., traitCollection: ...)`
    static func card_suit0_rank9(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.card_suit0_rank9, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "card_suit1_rank0", bundle: ..., traitCollection: ...)`
    static func card_suit1_rank0(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.card_suit1_rank0, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "card_suit1_rank1", bundle: ..., traitCollection: ...)`
    static func card_suit1_rank1(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.card_suit1_rank1, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "card_suit1_rank10", bundle: ..., traitCollection: ...)`
    static func card_suit1_rank10(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.card_suit1_rank10, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "card_suit1_rank11", bundle: ..., traitCollection: ...)`
    static func card_suit1_rank11(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.card_suit1_rank11, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "card_suit1_rank12", bundle: ..., traitCollection: ...)`
    static func card_suit1_rank12(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.card_suit1_rank12, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "card_suit1_rank2", bundle: ..., traitCollection: ...)`
    static func card_suit1_rank2(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.card_suit1_rank2, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "card_suit1_rank3", bundle: ..., traitCollection: ...)`
    static func card_suit1_rank3(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.card_suit1_rank3, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "card_suit1_rank4", bundle: ..., traitCollection: ...)`
    static func card_suit1_rank4(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.card_suit1_rank4, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "card_suit1_rank5", bundle: ..., traitCollection: ...)`
    static func card_suit1_rank5(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.card_suit1_rank5, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "card_suit1_rank6", bundle: ..., traitCollection: ...)`
    static func card_suit1_rank6(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.card_suit1_rank6, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "card_suit1_rank7", bundle: ..., traitCollection: ...)`
    static func card_suit1_rank7(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.card_suit1_rank7, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "card_suit1_rank8", bundle: ..., traitCollection: ...)`
    static func card_suit1_rank8(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.card_suit1_rank8, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "card_suit1_rank9", bundle: ..., traitCollection: ...)`
    static func card_suit1_rank9(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.card_suit1_rank9, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "card_suit2_rank0", bundle: ..., traitCollection: ...)`
    static func card_suit2_rank0(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.card_suit2_rank0, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "card_suit2_rank1", bundle: ..., traitCollection: ...)`
    static func card_suit2_rank1(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.card_suit2_rank1, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "card_suit2_rank10", bundle: ..., traitCollection: ...)`
    static func card_suit2_rank10(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.card_suit2_rank10, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "card_suit2_rank11", bundle: ..., traitCollection: ...)`
    static func card_suit2_rank11(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.card_suit2_rank11, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "card_suit2_rank12", bundle: ..., traitCollection: ...)`
    static func card_suit2_rank12(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.card_suit2_rank12, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "card_suit2_rank2", bundle: ..., traitCollection: ...)`
    static func card_suit2_rank2(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.card_suit2_rank2, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "card_suit2_rank3", bundle: ..., traitCollection: ...)`
    static func card_suit2_rank3(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.card_suit2_rank3, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "card_suit2_rank4", bundle: ..., traitCollection: ...)`
    static func card_suit2_rank4(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.card_suit2_rank4, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "card_suit2_rank5", bundle: ..., traitCollection: ...)`
    static func card_suit2_rank5(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.card_suit2_rank5, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "card_suit2_rank6", bundle: ..., traitCollection: ...)`
    static func card_suit2_rank6(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.card_suit2_rank6, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "card_suit2_rank7", bundle: ..., traitCollection: ...)`
    static func card_suit2_rank7(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.card_suit2_rank7, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "card_suit2_rank8", bundle: ..., traitCollection: ...)`
    static func card_suit2_rank8(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.card_suit2_rank8, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "card_suit2_rank9", bundle: ..., traitCollection: ...)`
    static func card_suit2_rank9(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.card_suit2_rank9, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "card_suit3_rank0", bundle: ..., traitCollection: ...)`
    static func card_suit3_rank0(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.card_suit3_rank0, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "card_suit3_rank1", bundle: ..., traitCollection: ...)`
    static func card_suit3_rank1(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.card_suit3_rank1, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "card_suit3_rank10", bundle: ..., traitCollection: ...)`
    static func card_suit3_rank10(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.card_suit3_rank10, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "card_suit3_rank11", bundle: ..., traitCollection: ...)`
    static func card_suit3_rank11(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.card_suit3_rank11, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "card_suit3_rank12", bundle: ..., traitCollection: ...)`
    static func card_suit3_rank12(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.card_suit3_rank12, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "card_suit3_rank2", bundle: ..., traitCollection: ...)`
    static func card_suit3_rank2(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.card_suit3_rank2, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "card_suit3_rank3", bundle: ..., traitCollection: ...)`
    static func card_suit3_rank3(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.card_suit3_rank3, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "card_suit3_rank4", bundle: ..., traitCollection: ...)`
    static func card_suit3_rank4(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.card_suit3_rank4, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "card_suit3_rank5", bundle: ..., traitCollection: ...)`
    static func card_suit3_rank5(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.card_suit3_rank5, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "card_suit3_rank6", bundle: ..., traitCollection: ...)`
    static func card_suit3_rank6(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.card_suit3_rank6, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "card_suit3_rank7", bundle: ..., traitCollection: ...)`
    static func card_suit3_rank7(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.card_suit3_rank7, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "card_suit3_rank8", bundle: ..., traitCollection: ...)`
    static func card_suit3_rank8(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.card_suit3_rank8, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "card_suit3_rank9", bundle: ..., traitCollection: ...)`
    static func card_suit3_rank9(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.card_suit3_rank9, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "iTunesArtwork", bundle: ..., traitCollection: ...)`
    static func iTunesArtwork(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.iTunesArtwork, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "icon_chip_blue", bundle: ..., traitCollection: ...)`
    static func icon_chip_blue(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.icon_chip_blue, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "icon_done_blue", bundle: ..., traitCollection: ...)`
    static func icon_done_blue(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.icon_done_blue, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "icon_done_green", bundle: ..., traitCollection: ...)`
    static func icon_done_green(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.icon_done_green, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "icon_leaderboards_blue", bundle: ..., traitCollection: ...)`
    static func icon_leaderboards_blue(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.icon_leaderboards_blue, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "icon_play", bundle: ..., traitCollection: ...)`
    static func icon_play(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.icon_play, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "icon_share_facebook_large", bundle: ..., traitCollection: ...)`
    static func icon_share_facebook_large(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.icon_share_facebook_large, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "icon_share_facebook_small", bundle: ..., traitCollection: ...)`
    static func icon_share_facebook_small(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.icon_share_facebook_small, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "icon_share_instagram_large", bundle: ..., traitCollection: ...)`
    static func icon_share_instagram_large(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.icon_share_instagram_large, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "icon_share_instagram_small", bundle: ..., traitCollection: ...)`
    static func icon_share_instagram_small(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.icon_share_instagram_small, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "icon_share_twitter_large", bundle: ..., traitCollection: ...)`
    static func icon_share_twitter_large(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.icon_share_twitter_large, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "icon_share_twitter_small", bundle: ..., traitCollection: ...)`
    static func icon_share_twitter_small(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.icon_share_twitter_small, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "icon_stats", bundle: ..., traitCollection: ...)`
    static func icon_stats(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.icon_stats, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "icon_stats_blue", bundle: ..., traitCollection: ...)`
    static func icon_stats_blue(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.icon_stats_blue, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "icon_stats_green", bundle: ..., traitCollection: ...)`
    static func icon_stats_green(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.icon_stats_green, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "launch_screen", bundle: ..., traitCollection: ...)`
    static func launch_screen(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.launch_screen, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "overlay_letters_blue", bundle: ..., traitCollection: ...)`
    static func overlay_letters_blue(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.overlay_letters_blue, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "overlay_stats_level_1", bundle: ..., traitCollection: ...)`
    static func overlay_stats_level_1(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.overlay_stats_level_1, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "overlay_stats_level_2", bundle: ..., traitCollection: ...)`
    static func overlay_stats_level_2(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.overlay_stats_level_2, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "overlay_stats_level_3", bundle: ..., traitCollection: ...)`
    static func overlay_stats_level_3(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.overlay_stats_level_3, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "overlay_stats_level_4", bundle: ..., traitCollection: ...)`
    static func overlay_stats_level_4(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.overlay_stats_level_4, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "overlay_stats_level_5", bundle: ..., traitCollection: ...)`
    static func overlay_stats_level_5(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.overlay_stats_level_5, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "overlay_stats_level_6", bundle: ..., traitCollection: ...)`
    static func overlay_stats_level_6(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.overlay_stats_level_6, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "overlay_stats_level_7", bundle: ..., traitCollection: ...)`
    static func overlay_stats_level_7(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.overlay_stats_level_7, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "overlay_stats_level_overall", bundle: ..., traitCollection: ...)`
    static func overlay_stats_level_overall(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.overlay_stats_level_overall, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "overlay_stats_locked_level_2", bundle: ..., traitCollection: ...)`
    static func overlay_stats_locked_level_2(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.overlay_stats_locked_level_2, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "overlay_stats_locked_level_3", bundle: ..., traitCollection: ...)`
    static func overlay_stats_locked_level_3(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.overlay_stats_locked_level_3, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "overlay_stats_locked_level_4", bundle: ..., traitCollection: ...)`
    static func overlay_stats_locked_level_4(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.overlay_stats_locked_level_4, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "overlay_stats_locked_level_5", bundle: ..., traitCollection: ...)`
    static func overlay_stats_locked_level_5(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.overlay_stats_locked_level_5, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "overlay_stats_locked_level_6", bundle: ..., traitCollection: ...)`
    static func overlay_stats_locked_level_6(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.overlay_stats_locked_level_6, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "overlay_stats_locked_level_7", bundle: ..., traitCollection: ...)`
    static func overlay_stats_locked_level_7(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.overlay_stats_locked_level_7, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "overlay_table_level_1", bundle: ..., traitCollection: ...)`
    static func overlay_table_level_1(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.overlay_table_level_1, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "overlay_table_level_2", bundle: ..., traitCollection: ...)`
    static func overlay_table_level_2(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.overlay_table_level_2, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "overlay_table_level_3", bundle: ..., traitCollection: ...)`
    static func overlay_table_level_3(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.overlay_table_level_3, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "overlay_table_level_4", bundle: ..., traitCollection: ...)`
    static func overlay_table_level_4(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.overlay_table_level_4, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "overlay_table_level_5", bundle: ..., traitCollection: ...)`
    static func overlay_table_level_5(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.overlay_table_level_5, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "overlay_table_level_6", bundle: ..., traitCollection: ...)`
    static func overlay_table_level_6(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.overlay_table_level_6, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "overlay_table_level_7", bundle: ..., traitCollection: ...)`
    static func overlay_table_level_7(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.overlay_table_level_7, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "overlay_table_locked_level_2", bundle: ..., traitCollection: ...)`
    static func overlay_table_locked_level_2(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.overlay_table_locked_level_2, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "overlay_table_locked_level_3", bundle: ..., traitCollection: ...)`
    static func overlay_table_locked_level_3(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.overlay_table_locked_level_3, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "overlay_table_locked_level_4", bundle: ..., traitCollection: ...)`
    static func overlay_table_locked_level_4(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.overlay_table_locked_level_4, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "overlay_table_locked_level_5", bundle: ..., traitCollection: ...)`
    static func overlay_table_locked_level_5(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.overlay_table_locked_level_5, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "overlay_table_locked_level_6", bundle: ..., traitCollection: ...)`
    static func overlay_table_locked_level_6(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.overlay_table_locked_level_6, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "overlay_table_locked_level_7", bundle: ..., traitCollection: ...)`
    static func overlay_table_locked_level_7(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.overlay_table_locked_level_7, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "shadow_blue", bundle: ..., traitCollection: ...)`
    static func shadow_blue(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.shadow_blue, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "share_screen_instagram", bundle: ..., traitCollection: ...)`
    static func share_screen_instagram(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.share_screen_instagram, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "share_screen_twitter", bundle: ..., traitCollection: ...)`
    static func share_screen_twitter(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.share_screen_twitter, compatibleWithTraitCollection: traitCollection)
    }
    
    private init() {}
  }
  
  private struct intern: Rswift.Validatable {
    static func validate() throws {
      try _R.validate()
    }
    
    private init() {}
  }
  
  /// This `R.nib` struct is generated, and contains static references to 1 nibs.
  struct nib {
    /// Nib `TextBannerView`.
    static let textBannerView = _R.nib._TextBannerView()
    
    /// `UINib(name: "TextBannerView", bundle: ...)`
    static func textBannerView(_: Void) -> UINib {
      return UINib(resource: R.nib.textBannerView)
    }
    
    private init() {}
  }
  
  /// This `R.reuseIdentifier` struct is generated, and contains static references to 3 reuse identifiers.
  struct reuseIdentifier {
    /// Reuse identifier `HandCell`.
    static let handCell: ReuseIdentifier<HandCell> = ReuseIdentifier(identifier: "HandCell")
    /// Reuse identifier `LevelCell`.
    static let levelCell: ReuseIdentifier<LevelCell> = ReuseIdentifier(identifier: "LevelCell")
    /// Reuse identifier `StatsCell`.
    static let statsCell: ReuseIdentifier<StatsCell> = ReuseIdentifier(identifier: "StatsCell")
    
    private init() {}
  }
  
  /// This `R.segue` struct is generated, and contains static references to 3 view controllers.
  struct segue {
    /// This struct is generated for `GameScreen`, and contains static references to 2 segues.
    struct gameScreen {
      /// Segue identifier `FirstHands`.
      static let firstHands: StoryboardSegueIdentifier<UIStoryboardSegue, GameScreen, HandsViewController> = StoryboardSegueIdentifier(identifier: "FirstHands")
      /// Segue identifier `SecondHands`.
      static let secondHands: StoryboardSegueIdentifier<UIStoryboardSegue, GameScreen, HandsViewController> = StoryboardSegueIdentifier(identifier: "SecondHands")
      
      /// Optionally returns a typed version of segue `FirstHands`.
      /// Returns nil if either the segue identifier, the source, destination, or segue types don't match.
      /// For use inside `prepareForSegue(segue: UIStoryboardSegue, sender: AnyObject?)`.
      static func firstHands(segue segue: UIStoryboardSegue) -> TypedStoryboardSegueInfo<UIStoryboardSegue, GameScreen, HandsViewController>? {
        return TypedStoryboardSegueInfo(segueIdentifier: R.segue.gameScreen.firstHands, segue: segue)
      }
      
      /// Optionally returns a typed version of segue `SecondHands`.
      /// Returns nil if either the segue identifier, the source, destination, or segue types don't match.
      /// For use inside `prepareForSegue(segue: UIStoryboardSegue, sender: AnyObject?)`.
      static func secondHands(segue segue: UIStoryboardSegue) -> TypedStoryboardSegueInfo<UIStoryboardSegue, GameScreen, HandsViewController>? {
        return TypedStoryboardSegueInfo(segueIdentifier: R.segue.gameScreen.secondHands, segue: segue)
      }
      
      private init() {}
    }
    
    /// This struct is generated for `MainScreen`, and contains static references to 3 segues.
    struct mainScreen {
      /// Segue identifier `Levels`.
      static let levels: StoryboardSegueIdentifier<UIStoryboardSegue, MainScreen, LevelsViewController> = StoryboardSegueIdentifier(identifier: "Levels")
      /// Segue identifier `Sharing`.
      static let sharing: StoryboardSegueIdentifier<UIStoryboardSegue, MainScreen, SharingViewController> = StoryboardSegueIdentifier(identifier: "Sharing")
      /// Segue identifier `Stats`.
      static let stats: StoryboardSegueIdentifier<UIStoryboardSegue, MainScreen, StatsViewController> = StoryboardSegueIdentifier(identifier: "Stats")
      
      /// Optionally returns a typed version of segue `Levels`.
      /// Returns nil if either the segue identifier, the source, destination, or segue types don't match.
      /// For use inside `prepareForSegue(segue: UIStoryboardSegue, sender: AnyObject?)`.
      static func levels(segue segue: UIStoryboardSegue) -> TypedStoryboardSegueInfo<UIStoryboardSegue, MainScreen, LevelsViewController>? {
        return TypedStoryboardSegueInfo(segueIdentifier: R.segue.mainScreen.levels, segue: segue)
      }
      
      /// Optionally returns a typed version of segue `Sharing`.
      /// Returns nil if either the segue identifier, the source, destination, or segue types don't match.
      /// For use inside `prepareForSegue(segue: UIStoryboardSegue, sender: AnyObject?)`.
      static func sharing(segue segue: UIStoryboardSegue) -> TypedStoryboardSegueInfo<UIStoryboardSegue, MainScreen, SharingViewController>? {
        return TypedStoryboardSegueInfo(segueIdentifier: R.segue.mainScreen.sharing, segue: segue)
      }
      
      /// Optionally returns a typed version of segue `Stats`.
      /// Returns nil if either the segue identifier, the source, destination, or segue types don't match.
      /// For use inside `prepareForSegue(segue: UIStoryboardSegue, sender: AnyObject?)`.
      static func stats(segue segue: UIStoryboardSegue) -> TypedStoryboardSegueInfo<UIStoryboardSegue, MainScreen, StatsViewController>? {
        return TypedStoryboardSegueInfo(segueIdentifier: R.segue.mainScreen.stats, segue: segue)
      }
      
      private init() {}
    }
    
    /// This struct is generated for `StatsScreen`, and contains static references to 1 segues.
    struct statsScreen {
      /// Segue identifier `Stats`.
      static let stats: StoryboardSegueIdentifier<UIStoryboardSegue, StatsScreen, StatsViewController> = StoryboardSegueIdentifier(identifier: "Stats")
      
      /// Optionally returns a typed version of segue `Stats`.
      /// Returns nil if either the segue identifier, the source, destination, or segue types don't match.
      /// For use inside `prepareForSegue(segue: UIStoryboardSegue, sender: AnyObject?)`.
      static func stats(segue segue: UIStoryboardSegue) -> TypedStoryboardSegueInfo<UIStoryboardSegue, StatsScreen, StatsViewController>? {
        return TypedStoryboardSegueInfo(segueIdentifier: R.segue.statsScreen.stats, segue: segue)
      }
      
      private init() {}
    }
    
    private init() {}
  }
  
  /// This `R.storyboard` struct is generated, and contains static references to 2 storyboards.
  struct storyboard {
    /// Storyboard `LaunchScreen`.
    static let launchScreen = _R.storyboard.launchScreen()
    /// Storyboard `Main`.
    static let main = _R.storyboard.main()
    
    /// `UIStoryboard(name: "LaunchScreen", bundle: ...)`
    static func launchScreen(_: Void) -> UIStoryboard {
      return UIStoryboard(resource: R.storyboard.launchScreen)
    }
    
    /// `UIStoryboard(name: "Main", bundle: ...)`
    static func main(_: Void) -> UIStoryboard {
      return UIStoryboard(resource: R.storyboard.main)
    }
    
    private init() {}
  }
  
  /// This `R.string` struct is generated, and contains static references to 1 localization tables.
  struct string {
    /// This `R.string.localizable` struct is generated, and contains static references to 17 localization keys.
    struct localizable {
      /// Value: HoldemHands
      static let appName = StringResource(key: "app.name", tableName: "Localizable", locales: [])
      /// Value: You need %@ chips more to unlock %@
      static let bannerChipsToUnlockLevel = StringResource(key: "banner.chips.to.unlock.level", tableName: "Localizable", locales: [])
      /// Value: Congratulations! You've unlocked %@!
      static let bannerUnlockedLevel = StringResource(key: "banner.unlocked.level", tableName: "Localizable", locales: [])
      /// Value: Welcome! Choose better hand to win the round
      static let bannerWalkthroughChooseHand = StringResource(key: "banner.walkthrough.choose.hand", tableName: "Localizable", locales: [])
      /// Value: Nice Try... Tap or Swipe to play next hand
      static let bannerWalkthroughLost = StringResource(key: "banner.walkthrough.lost", tableName: "Localizable", locales: [])
      /// Value: Good Job! Tap or Swipe to play next hand
      static let bannerWalkthroughWon = StringResource(key: "banner.walkthrough.won", tableName: "Localizable", locales: [])
      /// Value: Unable to locate your Facebook account
      static let errorShareWithFacebook = StringResource(key: "error.share.with.facebook", tableName: "Localizable", locales: [])
      /// Value: Unable to locate your Instagram account
      static let errorShareWithInstagram = StringResource(key: "error.share.with.instagram", tableName: "Localizable", locales: [])
      /// Value: Unable to locate your Twitter account
      static let errorShareWithTwitter = StringResource(key: "error.share.with.twitter", tableName: "Localizable", locales: [])
      /// Value: Tie: %.2f%%
      static let textTieOdds = StringResource(key: "text.tie.odds", tableName: "Localizable", locales: [])
      /// Value: Win: %.2f%%
      static let textWinOdds = StringResource(key: "text.win.odds", tableName: "Localizable", locales: [])
      /// Value: Play
      static let titleDetailsLevels = StringResource(key: "title.details.levels", tableName: "Localizable", locales: [])
      /// Value: Share
      static let titleDetailsSharing = StringResource(key: "title.details.sharing", tableName: "Localizable", locales: [])
      /// Value: Stats
      static let titleDetailsStats = StringResource(key: "title.details.stats", tableName: "Localizable", locales: [])
      /// Value: Play HoldemHands - prove your mastery!
      static let titleSharingFacebook = StringResource(key: "title.sharing.facebook", tableName: "Localizable", locales: [])
      /// Value: Play #HoldemHands - prove your mastery!
      static let titleSharingInstagram = StringResource(key: "title.sharing.instagram", tableName: "Localizable", locales: [])
      /// Value: Play @HoldemHands - prove your mastery!
      static let titleSharingTwitter = StringResource(key: "title.sharing.twitter", tableName: "Localizable", locales: [])
      
      /// Value: HoldemHands
      static func appName(_: Void) -> String {
        return NSLocalizedString("app.name", comment: "")
      }
      
      /// Value: You need %@ chips more to unlock %@
      static func bannerChipsToUnlockLevel(value1: String, _ value2: String) -> String {
        return String(format: NSLocalizedString("banner.chips.to.unlock.level", comment: ""), locale: NSLocale.currentLocale(), value1, value2)
      }
      
      /// Value: Congratulations! You've unlocked %@!
      static func bannerUnlockedLevel(value1: String) -> String {
        return String(format: NSLocalizedString("banner.unlocked.level", comment: ""), locale: NSLocale.currentLocale(), value1)
      }
      
      /// Value: Welcome! Choose better hand to win the round
      static func bannerWalkthroughChooseHand(_: Void) -> String {
        return NSLocalizedString("banner.walkthrough.choose.hand", comment: "")
      }
      
      /// Value: Nice Try... Tap or Swipe to play next hand
      static func bannerWalkthroughLost(_: Void) -> String {
        return NSLocalizedString("banner.walkthrough.lost", comment: "")
      }
      
      /// Value: Good Job! Tap or Swipe to play next hand
      static func bannerWalkthroughWon(_: Void) -> String {
        return NSLocalizedString("banner.walkthrough.won", comment: "")
      }
      
      /// Value: Unable to locate your Facebook account
      static func errorShareWithFacebook(_: Void) -> String {
        return NSLocalizedString("error.share.with.facebook", comment: "")
      }
      
      /// Value: Unable to locate your Instagram account
      static func errorShareWithInstagram(_: Void) -> String {
        return NSLocalizedString("error.share.with.instagram", comment: "")
      }
      
      /// Value: Unable to locate your Twitter account
      static func errorShareWithTwitter(_: Void) -> String {
        return NSLocalizedString("error.share.with.twitter", comment: "")
      }
      
      /// Value: Tie: %.2f%%
      static func textTieOdds(value1: Double) -> String {
        return String(format: NSLocalizedString("text.tie.odds", comment: ""), locale: NSLocale.currentLocale(), value1)
      }
      
      /// Value: Win: %.2f%%
      static func textWinOdds(value1: Double) -> String {
        return String(format: NSLocalizedString("text.win.odds", comment: ""), locale: NSLocale.currentLocale(), value1)
      }
      
      /// Value: Play
      static func titleDetailsLevels(_: Void) -> String {
        return NSLocalizedString("title.details.levels", comment: "")
      }
      
      /// Value: Share
      static func titleDetailsSharing(_: Void) -> String {
        return NSLocalizedString("title.details.sharing", comment: "")
      }
      
      /// Value: Stats
      static func titleDetailsStats(_: Void) -> String {
        return NSLocalizedString("title.details.stats", comment: "")
      }
      
      /// Value: Play HoldemHands - prove your mastery!
      static func titleSharingFacebook(_: Void) -> String {
        return NSLocalizedString("title.sharing.facebook", comment: "")
      }
      
      /// Value: Play #HoldemHands - prove your mastery!
      static func titleSharingInstagram(_: Void) -> String {
        return NSLocalizedString("title.sharing.instagram", comment: "")
      }
      
      /// Value: Play @HoldemHands - prove your mastery!
      static func titleSharingTwitter(_: Void) -> String {
        return NSLocalizedString("title.sharing.twitter", comment: "")
      }
      
      private init() {}
    }
    
    private init() {}
  }
  
  private init() {}
}

struct _R: Rswift.Validatable {
  static let hostingBundle = NSBundle(identifier: "com.visput.holdemhands.test") ?? NSBundle.mainBundle()
  
  static func validate() throws {
    try storyboard.validate()
  }
  
  struct nib {
    struct _TextBannerView: NibResourceType {
      let bundle = _R.hostingBundle
      let name = "TextBannerView"
      
      func firstView(owner ownerOrNil: AnyObject?, options optionsOrNil: [NSObject : AnyObject]? = nil) -> TextBannerView? {
        return instantiateWithOwner(ownerOrNil, options: optionsOrNil)[0] as? TextBannerView
      }
      
      private init() {}
    }
    
    private init() {}
  }
  
  struct storyboard: Rswift.Validatable {
    static func validate() throws {
      try main.validate()
      try launchScreen.validate()
    }
    
    struct launchScreen: StoryboardResourceWithInitialControllerType, Rswift.Validatable {
      typealias InitialController = UIViewController
      
      let bundle = _R.hostingBundle
      let name = "LaunchScreen"
      
      static func validate() throws {
        if UIImage(named: "launch_screen") == nil { throw ValidationError(description: "[R.swift] Image named 'launch_screen' is used in storyboard 'LaunchScreen', but couldn't be loaded.") }
      }
      
      private init() {}
    }
    
    struct main: StoryboardResourceWithInitialControllerType, Rswift.Validatable {
      typealias InitialController = UINavigationController
      
      let bundle = _R.hostingBundle
      let gameScreen = StoryboardViewControllerResource<GameScreen>(identifier: "GameScreen")
      let mainScreen = StoryboardViewControllerResource<MainScreen>(identifier: "MainScreen")
      let name = "Main"
      let statsScreen = StoryboardViewControllerResource<StatsScreen>(identifier: "StatsScreen")
      
      func gameScreen(_: Void) -> GameScreen? {
        return UIStoryboard(resource: self).instantiateViewController(gameScreen)
      }
      
      func mainScreen(_: Void) -> MainScreen? {
        return UIStoryboard(resource: self).instantiateViewController(mainScreen)
      }
      
      func statsScreen(_: Void) -> StatsScreen? {
        return UIStoryboard(resource: self).instantiateViewController(statsScreen)
      }
      
      static func validate() throws {
        if UIImage(named: "background_table_level_1") == nil { throw ValidationError(description: "[R.swift] Image named 'background_table_level_1' is used in storyboard 'Main', but couldn't be loaded.") }
        if UIImage(named: "icon_share_instagram_small") == nil { throw ValidationError(description: "[R.swift] Image named 'icon_share_instagram_small' is used in storyboard 'Main', but couldn't be loaded.") }
        if UIImage(named: "icon_chip_blue") == nil { throw ValidationError(description: "[R.swift] Image named 'icon_chip_blue' is used in storyboard 'Main', but couldn't be loaded.") }
        if UIImage(named: "icon_done_green") == nil { throw ValidationError(description: "[R.swift] Image named 'icon_done_green' is used in storyboard 'Main', but couldn't be loaded.") }
        if UIImage(named: "icon_share_twitter_large") == nil { throw ValidationError(description: "[R.swift] Image named 'icon_share_twitter_large' is used in storyboard 'Main', but couldn't be loaded.") }
        if UIImage(named: "icon_share_twitter_small") == nil { throw ValidationError(description: "[R.swift] Image named 'icon_share_twitter_small' is used in storyboard 'Main', but couldn't be loaded.") }
        if UIImage(named: "overlay_letters_blue") == nil { throw ValidationError(description: "[R.swift] Image named 'overlay_letters_blue' is used in storyboard 'Main', but couldn't be loaded.") }
        if UIImage(named: "icon_stats_green") == nil { throw ValidationError(description: "[R.swift] Image named 'icon_stats_green' is used in storyboard 'Main', but couldn't be loaded.") }
        if UIImage(named: "icon_done_blue") == nil { throw ValidationError(description: "[R.swift] Image named 'icon_done_blue' is used in storyboard 'Main', but couldn't be loaded.") }
        if UIImage(named: "button_menu_share_selected") == nil { throw ValidationError(description: "[R.swift] Image named 'button_menu_share_selected' is used in storyboard 'Main', but couldn't be loaded.") }
        if UIImage(named: "shadow_blue") == nil { throw ValidationError(description: "[R.swift] Image named 'shadow_blue' is used in storyboard 'Main', but couldn't be loaded.") }
        if UIImage(named: "background_blue") == nil { throw ValidationError(description: "[R.swift] Image named 'background_blue' is used in storyboard 'Main', but couldn't be loaded.") }
        if UIImage(named: "icon_play") == nil { throw ValidationError(description: "[R.swift] Image named 'icon_play' is used in storyboard 'Main', but couldn't be loaded.") }
        if UIImage(named: "card_back") == nil { throw ValidationError(description: "[R.swift] Image named 'card_back' is used in storyboard 'Main', but couldn't be loaded.") }
        if UIImage(named: "overlay_table_level_1") == nil { throw ValidationError(description: "[R.swift] Image named 'overlay_table_level_1' is used in storyboard 'Main', but couldn't be loaded.") }
        if UIImage(named: "icon_share_facebook_small") == nil { throw ValidationError(description: "[R.swift] Image named 'icon_share_facebook_small' is used in storyboard 'Main', but couldn't be loaded.") }
        if UIImage(named: "background_hand_odds_green") == nil { throw ValidationError(description: "[R.swift] Image named 'background_hand_odds_green' is used in storyboard 'Main', but couldn't be loaded.") }
        if UIImage(named: "button_menu_play_selected") == nil { throw ValidationError(description: "[R.swift] Image named 'button_menu_play_selected' is used in storyboard 'Main', but couldn't be loaded.") }
        if UIImage(named: "button_menu_stats_selected") == nil { throw ValidationError(description: "[R.swift] Image named 'button_menu_stats_selected' is used in storyboard 'Main', but couldn't be loaded.") }
        if UIImage(named: "icon_stats") == nil { throw ValidationError(description: "[R.swift] Image named 'icon_stats' is used in storyboard 'Main', but couldn't be loaded.") }
        if UIImage(named: "background_green") == nil { throw ValidationError(description: "[R.swift] Image named 'background_green' is used in storyboard 'Main', but couldn't be loaded.") }
        if UIImage(named: "button_menu_play_normal") == nil { throw ValidationError(description: "[R.swift] Image named 'button_menu_play_normal' is used in storyboard 'Main', but couldn't be loaded.") }
        if UIImage(named: "button_menu_share_normal") == nil { throw ValidationError(description: "[R.swift] Image named 'button_menu_share_normal' is used in storyboard 'Main', but couldn't be loaded.") }
        if UIImage(named: "icon_leaderboards_blue") == nil { throw ValidationError(description: "[R.swift] Image named 'icon_leaderboards_blue' is used in storyboard 'Main', but couldn't be loaded.") }
        if UIImage(named: "icon_share_facebook_large") == nil { throw ValidationError(description: "[R.swift] Image named 'icon_share_facebook_large' is used in storyboard 'Main', but couldn't be loaded.") }
        if UIImage(named: "button_menu_stats_normal") == nil { throw ValidationError(description: "[R.swift] Image named 'button_menu_stats_normal' is used in storyboard 'Main', but couldn't be loaded.") }
        if UIImage(named: "icon_share_instagram_large") == nil { throw ValidationError(description: "[R.swift] Image named 'icon_share_instagram_large' is used in storyboard 'Main', but couldn't be loaded.") }
        if UIImage(named: "overlay_stats_level_1") == nil { throw ValidationError(description: "[R.swift] Image named 'overlay_stats_level_1' is used in storyboard 'Main', but couldn't be loaded.") }
        if _R.storyboard.main().mainScreen() == nil { throw ValidationError(description:"[R.swift] ViewController with identifier 'mainScreen' could not be loaded from storyboard 'Main' as 'MainScreen'.") }
        if _R.storyboard.main().gameScreen() == nil { throw ValidationError(description:"[R.swift] ViewController with identifier 'gameScreen' could not be loaded from storyboard 'Main' as 'GameScreen'.") }
        if _R.storyboard.main().statsScreen() == nil { throw ValidationError(description:"[R.swift] ViewController with identifier 'statsScreen' could not be loaded from storyboard 'Main' as 'StatsScreen'.") }
      }
      
      private init() {}
    }
    
    private init() {}
  }
  
  private init() {}
}