//
//  UIColor+AppPalette.h
//
//  This source file is autogenerated.
//  Don't change this file manually.
//

import UIKit

extension UIColor {

    class func aquamarine1Color() -> UIColor {
        return UIColor(red: 0.5960784554481506,
            green:0.929411768913269,
            blue:0.8745098114013672,
            alpha:1)
    }

    class func gray1Color() -> UIColor {
        return UIColor(red: 0.8156862854957581,
            green:0.8509804010391235,
            blue:0.9372549057006836,
            alpha:1)
    }

    class func gray2Color() -> UIColor {
        return UIColor(red: 0.6470588445663452,
            green:0.6784313917160034,
            blue:0.7764706015586853,
            alpha:1)
    }

    class func green1Color() -> UIColor {
        return UIColor(red: 0.09411764889955521,
            green:0.6431372761726379,
            blue:0.4705882370471954,
            alpha:1)
    }

    class func green2Color() -> UIColor {
        return UIColor(red: 0.1333333402872086,
            green:0.843137264251709,
            blue:0.6235294342041016,
            alpha:1)
    }

    class func blue1Color() -> UIColor {
        return UIColor(red: 0.3607843220233917,
            green:0.4313725531101227,
            blue:0.6039215922355652,
            alpha:1)
    }

}
