//
//  UIColor+AppPalette.h
//
//  This source file is autogenerated.
//  Don't change this file manually.
//

import UIKit

extension UIColor {

    class func aquamarine1Color() -> UIColor {
        return UIColor(red: 0.5960784554481506,
            green:0.929411768913269,
            blue:0.8745098114013672,
            alpha:1)
    }

    class func gray1Color() -> UIColor {
        return UIColor(red: 0.8156862854957581,
            green:0.8509804010391235,
            blue:0.9372549057006836,
            alpha:1)
    }

}
